### ISSUE TITLE
对于WSA能否推出不进行音量键测试的包？

### ISSUE THREAD

**Issue by CuleSKY** [taoaoooo/microG_playStore_GoogleContactsSync_installer#1]
如题
WSA似乎无法模拟手机音量键
无法通过Magisk安装Google Play服务
能否推出针对WSA的版本？

**Comment by taoaoooo** [comment]
可以，上次忘了，马上好

**Comment by taoaoooo** [comment]
> 如题 WSA似乎无法模拟手机音量键 无法通过Magisk安装Google Play服务 能否推出针对WSA的版本？

可以，我要试试是内部解决好实现还是外部解决比较好

**Comment by taoaoooo** [comment]
> 如题 WSA似乎无法模拟手机音量键 无法通过Magisk安装Google Play服务 能否推出针对WSA的版本？

对了，是没有这个问题的，我刚刚看了下，我之前对这个物理操作是有做跳过处理的，点击屏幕或者返回，默认就是覆盖安装，而WSA原本就没有gapps，所以也不需要改什么shell命令。不过虽然默认返回就会显示已经安装好了，但是我还是在开始加个提示吧
